# Generated by Django 4.2.3 on 2023-08-11 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='photo_urls',
            new_name='photos',
        ),
    ]
