# Generated by Django 4.2.3 on 2023-08-11 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_photo_urls_hotel_photos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attraction',
            old_name='photo_urls',
            new_name='photos',
        ),
    ]
