# Generated by Django 4.2.3 on 2023-08-11 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_photo_urls_attraction_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='opening_hours',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
