version: "3.9"

services:
  # Django backend service
  backend:
    build:
      context: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis

  # React frontend service
  frontend:
    build:
      context: ./app
    command: npm start
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx-setup.config:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
      - frontend

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
